spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:yu-quiz}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:}

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.naver.com

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_KEY:exampleSecretKeyForYUQuizSystemAccessSecretKeyTestForPadding}
  access-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  issuer: ${JWT_ISSUER:yu-quiz}

token:
  refresh:
    in-cookie: ${COOKIE_REFRESH_EXPIRATION:648000}
    in-redis: ${REDIS_REFRESH_EXPIRATION:648000}
  blacklist:
    in-redis: ${REDIS_BLACKLIST_EXPIRATION:3600}

cache:
  ttl: ${CACHE_TTL:60}

mail:
  reset-password:
    link: ${RESET_PASSWORD_LINK}

oauth2:
  kakao:
    tokenUri: https://kauth.kakao.com/oauth/token
    clientId: ${KAKAO_CLIENT_ID}
    clientSecret: ${KAKAO_CLIENT_SECRET}
    redirectUri: ${KAKAO_REDIRECT_URL}
    getUserInfoUri: https://kapi.kakao.com/v2/user/me

  naver:
    tokenUri: https://nid.naver.com/oauth2.0/token
    clientId: ${NAVER_CLIENT_ID}
    clientSecret: ${NAVER_CLIENT_SECRET}
    redirectUri: ${NAVER_REDIRECT_URL}
    getUserInfoUri: https://openapi.naver.com/v1/nid/me

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket-name: ${S3_BUCKET_NAME}